version: "3.9"

services:
  mariadb:
    container_name: Development-MariaDB
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Newspaper5
      MYSQL_USER: client
      MYSQL_PASSWORD: clientPassword5!
    volumes:
     - './mariadb_data/:/var/lib/mysql/'
    ports:
      [
        3307:3306,
        33070:33060
      ]
    networks:
      - db-init-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "192.168.1.136", "--port", "3307"]
      interval: 10s
      timeout: 5s
      retries: 5

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../csv_data:/csv_data:rw
      - ../schema:/schema:rw
      - ../development_db:/development_db:rw
    networks:
      - db-init-network
    depends_on:
      mariadb:
        condition: service_healthy
    command: python3 load_db.py force
    stdin_open: true
    tty: true

networks:
  db-init-network:
    driver: bridge