CREATE USER $(DB_USER)@'%' IDENTIFIED BY $(DB_PASSWORD);
GRANT ALL PRIVILEGES ON *.* TO $(DB_USER)@'%';
FLUSH PRIVILEGES;
-- CREATE USER 'dallasj'@'%' IDENTIFIED BY 'dallasjPassword!5';
-- GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'dallasj'@'%';
-- FLUSH PRIVILEGES;