/*
-- Query: SELECT * FROM Organizations.People
LIMIT 0, 400

-- Date: 2023-01-31 08:58
*/
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (1,1,'Kathy','Jensen','2023-01-27 09:26:26','Owner','Client Relations, Purchasing','8016025244','','info@holisticlifesupplements.com','',NULL,1,NULL,NULL,'');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (2,1,'Steven','Jensen','2023-01-27 09:26:26','Owner','Client Relations, Purchasing','8017873151','','stevej@prolifixnutrition.com','',NULL,1,NULL,NULL,'');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (3,1,'Ian','Bull','2023-01-27 09:26:26','Manager','Maintenance, Human Recources, Production','9285645378','','ianbullpn@gmail.com','',NULL,1,NULL,NULL,'');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (4,1,'Nathaniel','Reeves','2023-01-27 09:26:26','Manager','Quality, Information Technology, Software Development','8013801953','','nathaniel.jacob.reeves@gmail.com','',NULL,1,NULL,NULL,'10399');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (5,1,'Anna','Thayer','2023-01-27 09:26:26','Batcher','Production','4352293919','','','',NULL,1,NULL,NULL,'9188');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (6,1,'Coby','Thayer','2023-01-27 09:26:26','Team Lead','Production','4352159484','','','',NULL,1,NULL,NULL,'9187');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (7,1,'Benjamin','Black','2023-01-27 09:26:26','Staff','Production','4356164236','','','',NULL,1,NULL,NULL,'9186');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (8,1,'James','Beckstrand','2023-01-27 09:26:26','Staff','Production','','','','',NULL,1,NULL,NULL,'10568');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (9,1,'Sage','Stockard','2023-01-27 09:26:26','Staff','Production','','','','',NULL,1,NULL,NULL,'12475');
INSERT INTO `Organizations`.`People` (`person_id`,`organization_id`,`first_name`,`last_name`,`date_entered`,`job_description`,`department`,`phone_number_primary`,`phone_number_secondary`,`email_address_primary`,`email_address_secondary`,`birthday`,`is_employee`,`contract_date`,`termination_date`,`clock_number`) VALUES (10,1,'Jason','Hare','2023-01-27 09:26:26','Staff','Production','','','','',NULL,1,NULL,NULL,'12460');
