const productDoc = {
  labels: {
    date_issued: null,
    date_revised: null,
    notes: null,
    num_label_versions: 0,
    num_pouch_versions: 0,
    num_carton_versions: 0,
    num_promotional_versions: 0,
    all_labels: []
  },
  formula_files: [],
  manufacturing_files: [],
  specifications: {
    date_issued: '',
    date_revised: '',
    file_pointer: '',
    revision_number: 0,
    id_code: '',
    description_statement: '',
    identity_statement: 'This ingredient is identified by in house organoleptic specs and microscopy specs.',
    purity_statement: 'This finished product is verified for purity via Certificate of Analysis and microscopy observation (checking for contaminating particles.) Both the raw powders and finished blended powder are tested in this way. We verify the supplier of every raw ingredient through a reviewed questionnaire and test the supplier\'s certificate of analysis on a random/skip lot basis.',
    strength_statement: 'Strength is not relevant to this ingredient.',
    origin: '',
    parts_used: '',
    specs: {
      example_cofas: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        id_code: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        test_name: 'Reference CofA\'s',
        tests: []
      },
      mesh_size: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        id_code: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        statement: 'While mesh size testing can vary across supplier C of A\'s, the coarsest powder in this finished product is tested using a _____ mesh, with ____ % passing through. This is reflected in our in house microscopy testing. There should be no extraneous foreign objects (microscopically or visible to the naked eye), granulating agents, fillers or excipients in this finished product without express disclosure on the label.',
        test_name: 'Mesh Size',
        tests: []
      },
      ftir: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'FTIR testing is not required for this finished product. The individual powders that compose this product may have been identity tested using FTIR and this will be specified on the supplier\'s C of A.',
        test_name: 'FTIR',
        methods: [
          'FTIR'
        ],
        tests: []
      },
      gluten: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'While a gluten spec is not required for this finished product, if the suppliers provides a C of A with gluten testing, we\'ll accept the specs below.',
        test_name: 'Gluten',
        tests: []
      },
      heavy_metals: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'While heavy metals specs are not required, if there are suspicions regarding powder/the supplier, we will test this finished product (and/or its composite ingredients) to verify quality. On these occasions we will accept the specs below.',
        test_name: 'Heavy Metals',
        tests: [
          {
            test_name: 'Arsenic (As)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Cadmium (Cd)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Lead (Pb)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Mercury (Hg)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Total Heavy Metals',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          }
        ]
      },
      hplc: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'HPLC testing is not required for this finished product. The individual powders that compose this product may have been identity tested using HPLC and this will be specified on the supplier\'s C of A.',
        test_name: 'HPLC',
        methods: [
          'HPLC'
        ],
        tests: []
      },
      hptlc: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'HPTLC testing is not required for this finished product. The individual powders that compose this product may have been identity tested using HPTLC and this will be specified on the supplier\'s C of A.',
        test_name: 'HPTLC',
        tests: []
      },
      microbiological: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Microbiological',
        tests: [
          {
            test_name: 'Aerobic Plate Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Total Plate Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Coliforms Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Escherichia Coli Count (E.Coli)',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Staphylococcus Count (Staph)',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Salmonella Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Mold Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Yeast Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Moisture/Loss on Drying',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: '%',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          }
        ]
      },
      microscopic: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: false,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        statement: 'Overall, the visual profile of this finished product under the microscope is a _______ powder. Typically, it has __________ with __________ . We expect this kind of visual profile for __________.',
        test_name: 'Microscopic',
        tests: []
      },
      nutritional_facts: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'third_party_lab',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Nutritional Assay',
        tests: []
      },
      organochlorines: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Organochlorines',
        tests: []
      },
      organoleptic: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        test_name: 'Organoleptic',
        tests: [
          {
            test_name: 'Organoleptic',
            statement: 'Overall, the visual organoleptic profile of this finished product is a ________ powder. It typically has a _______ odor and a ________ taste. We expect this kind of organoleptic profile for _________.',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          }
        ]
      },
      pesticides: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '[TEMPLATE]      However, to ensure this is the case, we test for pesticide residue on a skip lot basis (for each supplier company.) Ultimately, while pesticide specs are not required, if the supplier provides a C of A with pesticide testing, we\'ll accept the individual spec below.',
        test_name: 'Pesticides',
        tests: []
      },
      residual_solvents: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: 'Since this finished product is made from whole ingredients it\'s highly unlikely solvents were used at any point during production. Solvents are most often used in an extraction process that separates the natural constituents from a raw material (in an extract or concentrate.) This wouldn\'t be relevant for this product, which doesn\'t use extracts or concentrated powders; the typical way a powder is processed is through dehydration and grinding and therefore there should be no residual solvents.',
        test_name: 'Residual Solvents',
        tests: []
      }
    }
  }
}

export default productDoc
