version: "3.9"

services:

  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: '%'
    volumes:
      - './db/mariadb_data/:/var/lib/mysql/'
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      mrp:
        ipv4_address: 172.10.10.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "172.10.10.2", "--port", "3306", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

  init_db:
    container_name: init_db
    environment:
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: '172.10.10.2'
      DB_PORT: '3306'
    restart: "no"
    volumes:
        - './init_db:/init_db'
    build:
      context: .
      dockerfile: init_db/Dockerfile
    networks:
      - mrp
    depends_on:
      mariadb:
        condition: service_healthy
    tty: true

  api:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: .
      dockerfile: api/Dockerfile
    volumes:
        - './client/public:/api/client/public'
        - './db/files:/db/files'
    ports:
      - "5000"
    networks:
      - mrp
    depends_on:
      init_db:
        condition: service_completed_successfully
    tty: true

  # Nginx Service
  api-lb:
    container_name: api_lb
    image: nginx:latest
    restart: always
    volumes:
     - ./api/main/nginx.conf:/etc/nginx/nginx.conf:ro
     - './client/public:/public'
    depends_on:
      - api
    ports:
     - "5000:5000"
    networks:
      mrp:
        ipv4_address: 172.10.10.6
    tty: true

  # Nginx Service
  client:
    stdin_open: true
    restart: always
    container_name: client
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
        - './db/files:/db/files'
    networks:
      mrp:
        ipv4_address: 172.10.10.5
    depends_on:
      - api-lb
    ports:
      - "3000:3000"
    tty: true

  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    networks:
      mrp:
        ipv4_address: 172.10.10.3
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - api-lb

  # Nginx Service
  web-server:
    container_name: web_server
    depends_on:
      - client
    image: nginx:latest
    volumes:
     - ./webserver/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    tty: true
    ports:
      - "80:80"
    networks:
      mrp:
        ipv4_address: 172.10.10.4

networks:
  mrp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.10.0/16
          ip_range: 172.10.11.0/26
          gateway: 172.10.10.1