const ingredientDoc = {
  specifications: {
    date_issued: '',
    date_revised: '',
    file_pointer: '',
    revision_number: 0,
    id_code: '',
    description_statement: '',
    identity_statement: '',
    purity_statement: 'This ingredient is verified for purity via the supplier\'s Certificate of Analysis and through microscopy observation (checking for contaminating particles.) We verify this supplier through a reviewed questionnaire and verify the supplier\'s certificate of analysis on a random/skip lot basis.',
    strength_statement: '',
    origin: '',
    parts_used: '',
    specs: {
      example_cofas: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        id_code: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        test_name: 'Reference CofA\'s',
        tests: []
      },
      mesh_size: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        id_code: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        statement: '',
        test_name: 'Mesh Size',
        tests: []
      },
      ftir: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'FTIR',
        methods: [
          'FTIR'
        ],
        tests: []
      },
      gluten: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Gluten',
        tests: []
      },
      heavy_metals: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Heavy Metals',
        tests: [
          {
            test_name: 'Arsenic (As)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Cadmium (Cd)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Lead (Pb)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Mercury (Hg)',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Total Heavy Metals',
            statement: '[TEMPLATE]            While heavy metal specs are not required, if the supplier provides a test for heavy metals these are the specs we\'ll accept.',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: 'ppm',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          }
        ]
      },
      hplc: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'HPLC',
        methods: [
          'HPLC'
        ],
        tests: []
      },
      hptlc: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'HPTLC',
        tests: []
      },
      microbiological: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Microbiological',
        tests: [
          {
            test_name: 'Aerobic/Total Plate Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Coliforms Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Escherichia Coli Count (E.Coli)',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Staphylococcus Count (Staph)',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Salmonella Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Mold Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Yeast Count',
            statement: '',
            magnification: '',
            required_spec: true,
            method: '',
            methods: [],
            unit_of_measure: 'cfu/g',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          },
          {
            test_name: 'Moisture/Loss on Drying',
            statement: '',
            magnification: '',
            required_spec: false,
            method: '',
            methods: [],
            unit_of_measure: '%',
            count: 0,
            inequality: '<',
            sources: [],
            odor: '',
            taste_dissolved: '',
            taste_dry: '',
            visual: '',
            id_code: '',
            file_pointer: '',
            file_preview_pointer: '',
            date_issued: '',
            date_revised: ''
          }
        ]
      },
      microscopic: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: false,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Microscopic',
        tests: []
      },
      nutritional_facts: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'third_party_lab',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Nutritional Assay',
        tests: []
      },
      organochlorines: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Organochlorines',
        tests: []
      },
      organoleptic: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: true,
          primary: 'in_house',
          supplier: true,
          third_party_lab: false
        },
        required_spec: true,
        revision_number: 0,
        id_code: '',
        test_name: 'Organoleptic',
        tests: []
      },
      pesticides: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '[TEMPLATE]      However, to ensure this is the case, we test for pesticide residue on a skip lot basis (for each supplier company.) While pesticide specs are not required, if the supplier provides a C of A with pesticide testing, we\'ll accept the individual spec below.',
        test_name: 'Pesticides',
        tests: []
      },
      residual_solvents: {
        date_issued: '',
        date_revised: '',
        file_pointer: '',
        locations: {
          in_house: false,
          primary: 'supplier',
          supplier: true,
          third_party_lab: true
        },
        required_spec: false,
        revision_number: 0,
        id_code: '',
        statement: '',
        test_name: 'Residual Solvents',
        tests: []
      }
    }
  }
}

export default ingredientDoc
