name: Test & Build MRP System

on: [push]
  # push:
  #   # Pattern matched against refs/tags
  #   tags:        
  #     - '**'  # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/checkout@v4
      - name: Install MariaDB Connector Dependencies
        run: |
          sudo apt-get install -y curl
          sudo apt-get install -y apt-transport-https 
          sudo apt-get install -y wget
          sudo wget https://dlm.mariadb.com/3/MariaDB/mariadb_repo_setup
          sudo chmod +x mariadb_repo_setup
          sudo ./mariadb_repo_setup --os-type=debian --os-version=11 --arch=x86_64
          sudo apt-get install -y mariadb-client
          sudo apt-get install -y python3-pip
          sudo apt-get install -y --no-install-recommends \
            libmariadb3 \
            libmariadb-dev \
            && rm -rf /var/lib/apt/lists/*
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/api/tests/requirements.txt
          pip install pytest pytest-cov
      - name: Run Tests
        run: pytest app/api/tests --spec --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html