name: Test & Build MRP System

on: [push]

jobs:
  # unittest-API:
  #   uses: ./.github/workflows/test-api.yml
  # unittest-CLIENT:
  #   uses: ./.github/workflows/test-client.yml


  attempt-build:

    runs-on: self-hosted

    # needs: [
    #   unittest-API,
    #   unittest-CLIENT
    # ]
    
    steps:
      
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: View Old Images
        run: sudo docker image ls -a
      - name: Clean Old Images
        run: |
          'sudo docker image rm mariadb:10.11'
          sudo docker image prune
        continue-on-error: true
      - name: 'Create New env File'
        run: |
          sudo [ ! -e ./app/.env ] || sudo rm ./app/.env
          touch ./app/.env
          echo SSH_PRIVATE_KEY="" >> ./app/.env
          echo SSH_USER="" >> ./app/.env
          echo SSH_HOST="" >> ./app/.env
          echo WORK_DIR="" >> ./app/.env
          echo MAIN_BRANCH="" >> ./app/.env
          echo DB_ROOT_PASSWORD="Newspaper5" >> ./app/.env
          echo DB_HOST="172.10.10.2" >> ./app/.env
          echo DB_PORT="3306" >> ./app/.env
          echo DB_USER="client" >> ./app/.env
          echo DB_PASSWORD="ClientPassword!5" >> ./app/.env
          echo UPLOAD_FOLDER="/home/nathanr" >> ./app/.env
          echo REDIS_HOST="172.10.10.3" >> ./app/.env
          echo REDIS_PORT="6379" >> ./app/.env
          echo REDIS_PASSWORD="Am^7qq?%QgedcLn" >> ./app/.env
          echo API_PREFIX="False" >> ./app/.env
          echo API_CORS_KEY="0kgy23uJpIin346NeC7hUZ3Bak36S84N1X35k4kY" >> ./app/.env
      - name: View Env
        run: |
          cat ./app/.env
      - name: Attempt to Build MRP Project
        run: sudo docker compose -f app/docker-compose.yaml up -d --build
      - name: Stop Containers
        if: always()
        run: sudo docker compose -f app/docker-compose.yaml down
  
  # build-and-deploy:

  #   runs-on: ubuntu-latest

  #   needs: [
  #     attempt-build
  #   ]

  #   steps:
  #     - name: Checkout Project
  #       uses: actions/checkout@v2
  #     - name: Export Environment variables
  #       run: |
  #         export SSH_PRIVATE_KEY=
  #         export SSH_USER=
  #         export SSH_HOST=
  #         export WORK_DIR=
  #         export MAIN_BRANCH=
  #         export DB_ROOT_PASSWORD=
  #         export DB_HOST=
  #         export DB_PORT=
  #         export DB_USER=
  #         export DB_PASSWORD=
  #         export UPLOAD_FOLDER=
  #         export REDIS_HOST=
  #         export REDIS_PORT=
  #         export REDIS_PASSWORD=
  #         export API_PREFIX=
  #         export API_CORS_KEY=
