name: Test & Build MRP System

on: [push]
  # push:
  #   # Pattern matched against refs/tags
  #   tags:        
  #     - '**'  # Push events to every tag including hierarchical tags like v1.0/beta

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/api/tests/requirements.txt
          pip install pytest pytest-cov
      - name: Run Tests
        run: pytest app/api/tests --spec --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html