name: Test & Build MRP System

on: [push]

jobs:
  unittest-API:
    uses: ./.github/workflows/test-api.yml
  unittest-CLIENT:
    uses: ./.github/workflows/test-client.yml


  # attempt-build:

  #   runs-on: self-hosted

  #   needs: [
  #     unittest-API,
  #     unittest-CLIENT
  #   ]

  #   steps:
  #     - name: Complete Tests
  #       run: exit 0
    
    # steps:
    #   - name: Checkout Project
    #     uses: actions/checkout@v4
    #   - name: View Old Images
    #     run: sudo docker image ls -a
    #   - name: Clean Old Images
    #     run: |
    #       'sudo docker image rm mariadb:10.11'
    #       sudo docker image prune
    #     continue-on-error: true
    #   - name: 'Create New env File'
    #     run: |
    #       sudo [ ! -e ./app/.env ] || sudo rm ./app/.env
    #       touch ./app/.env
    #       echo SSH_PRIVATE_KEY="" >> ./app/.env
    #       echo SSH_USER="" >> ./app/.env
    #       echo SSH_HOST="" >> ./app/.env
    #       echo WORK_DIR="" >> ./app/.env
    #       echo MAIN_BRANCH="" >> ./app/.env
    #       echo DB_ROOT_PASSWORD=${SUPER_PASSWORD} >> ./app/.env
    #       echo DB_HOST="172.10.10.2" >> ./app/.env
    #       echo DB_PORT="3306" >> ./app/.env
    #       echo DB_USER="client" >> ./app/.env
    #       echo DB_PASSWORD=${SUPER_CLIENT_PASSWORD} >> ./app/.env
    #       echo UPLOAD_FOLDER="/var/samba_drive_share/MRP_DRIVE/MRP_DRIVE/" >> ./app/.env
    #       echo REDIS_HOST="172.10.10.3" >> ./app/.env
    #       echo REDIS_PORT="6379" >> ./app/.env
    #       echo REDIS_PASSWORD=${SUPER_PASSWORD} >> ./app/.env
    #       echo API_PREFIX="False" >> ./app/.env
    #       echo API_CORS_KEY=${SUPER_KEY} >> ./app/.env
    #   - name: View Env
    #     run: |
    #       cat ./app/.env
    #   - name: Attempt to Build MRP Project
    #     run: sudo docker compose -f app/docker-compose.yaml up -d --build
    #   - name: Stop Containers
    #     if: always()
    #     run: sudo docker compose -f app/docker-compose.yaml down

