name: Set Env Variables & Secrets

on: workflow_call

jobs:

  attempt-build:

    runs-on: self-hosted

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Export Environment variables
        run: |
          export SSH_PRIVATE_KEY=''
          export SSH_USER=''
          export SSH_HOST=''
          export WORK_DIR=''
          export MAIN_BRANCH=''
          export DB_ROOT_PASSWORD='Newspaper5'
          export DB_HOST='172.10.10.2'
          export DB_PORT='3306'
          export DB_USER='client'
          export DB_PASSWORD='ClientPassword!5'
          export UPLOAD_FOLDER='/home/nathanr'
          export REDIS_HOST='172.10.10.3'
          export REDIS_PORT='6379'
          export REDIS_PASSWORD='Am^7qq?%QgedcLn'
          export API_PREFIX='False'
          export API_CORS_KEY='0kgy23uJpIin346NeC7hUZ3Bak36S844NoeN1X35k4kY'