name: Test Client

on: workflow_call

jobs:

  test-CLIENT:

    runs-on: self-hosted

    env:
      SSH_PRIVATE_KEY: ''
      SSH_USER: ''
      SSH_HOST: ''
      WORK_DIR: ''
      MAIN_BRANCH: ''
      DB_ROOT_PASSWORD: ''
      DB_HOST: '172.10.10.2'
      DB_PORT: '3306'
      DB_USER: 'client'
      DB_PASSWORD: ''
      UPLOAD_FOLDER: '/home/nathanr'
      REDIS_HOST: '172.10.10.3'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: ''
      API_PREFIX: 'False'
      API_CORS_KEY: ''

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Echo TODO
        run: echo "TODO"