name: Test API Server

on: workflow_call

jobs:

  test-API:

    runs-on: self-hosted

    env:
      SSH_PRIVATE_KEY: ''
      SSH_USER: ''
      SSH_HOST: ''
      WORK_DIR: ''
      MAIN_BRANCH: ''
      DB_ROOT_PASSWORD: 'Newspaper5'
      DB_HOST: '172.10.10.2'
      DB_PORT: '3306'
      DB_USER: 'client'
      DB_PASSWORD: 'ClientPassword!5'
      UPLOAD_FOLDER: '/home/nathanr'
      REDIS_HOST: '172.10.10.3'
      REDIS_PORT: '6379'
      REDIS_PASSWORD: 'Am^7qq?%QgedcLn'
      API_PREFIX: 'False'
      API_CORS_KEY: '0kgy23uJpIin346NeC7hUZ3Bak36S844NoeN1X35k4kY'

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Install MariaDB Connector Dependencies
        run: |
          sudo apt install wget
          sudo apt-get update
          sudo wget https://dlm.mariadb.com/3/MariaDB/mariadb_repo_setup
          # echo "935944a2ab2b2a48a47f68711b43ad2d698c97f1c3a7d074b34058060c2ad21b  mariadb_repo_setup" \
          #   | sha256sum -c -
          sudo chmod +x mariadb_repo_setup
          sudo ./mariadb_repo_setup \
            --mariadb-server-version="mariadb-10.6"
          sudo apt-get install -y mariadb-server mariadb-client
          sudo apt-get install -y python3-pip
          sudo apt-get update
          sudo apt install -y --no-install-recommends libmariadb3 libmariadb-dev && sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/api/tests/requirements.txt
          pip install pytest pytest-cov
      - name: Run Tests
        run: pytest app/api/tests --spec --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html